name: Build and Publish APK
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get packages
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload APK to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
      - name: Publish release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.ref }}
          release_name: Release v${{ github.ref }}
          draft: false
          prerelease: false
