name: Build and Publish Android APK

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Get version code and name
        id: get_version
        run: |
          echo "::set-output name=version_code::$(grep 'versionCode:' android/app/build.gradle | awk '{print $2}')"
          echo "::set-output name=version_name::$(grep 'versionName:' android/app/build.gradle | awk '{print $2}')"
      - name: Build APK
        run: flutter build apk --release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version_name }}
          release_name: Release v${{ steps.get_version.outputs.version_name }}
          draft: false
          prerelease: false
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release-${{ steps.get_version.outputs.version_name }}.apk
          asset_content_type: application/vnd.android.package-archive
